name: Daily Random Code Generation

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:  # This enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Determine Trigger Source
      id: trigger_check
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          echo "Manually triggered, skipping random check."
          echo "proceed=true" >> $GITHUB_OUTPUT
        else
          echo "Scheduled run, checking if we should proceed."
          RANDOM_NUMBER=$(( RANDOM % 24 ))
          if [ "$RANDOM_NUMBER" -eq "0" ]; then
            echo "Proceeding with code generation"
            echo "proceed=true" >> $GITHUB_OUTPUT
          else
            echo "Skipping this run"
            echo "proceed=false" >> $GITHUB_OUTPUT
          fi
        fi

    - name: Set up Python
      if: steps.trigger_check.outputs.proceed == 'true'
      uses: actions/setup-python@v5  # Updated version to v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: steps.trigger_check.outputs.proceed == 'true'
      run: |
        pip install requests langchain openai beautifulsoup4 langchain_community

    - name: Check out repository
      if: steps.trigger_check.outputs.proceed == 'true'
      uses: actions/checkout@v4  # Updated version to v4

    - name: Run script
      if: steps.trigger_check.outputs.proceed == 'true'
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python generate_code.py

    - name: Commit and push changes
      if: steps.trigger_check.outputs.proceed == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Add code generated on $(date '+%Y-%m-%d %H:%M:%S')"
        git push
